I don't remember the context around this comment

diff --git a/base/bin/editfast b/base/bin/editfast
--- a/base/bin/editfast
+++ b/base/bin/editfast
@@ -13,5 +13,6 @@ then
     nano $@
   fi
 else
-  emacsclient -a nano $@
+    # why on earth doesn't *this* work at least?
+  emacsclient -a nano "$@" # || echo "suppressing exit error because maybe false"
 fi
