Track multiple versions of fzf keybindings file

diff --git a/base/bin/install-everything b/base/bin/install-everything
--- a/base/bin/install-everything
+++ b/base/bin/install-everything
@@ -389,19 +389,16 @@ do
   if [ "$1" == "all" -o "$1" == "server" -o "$1" == "fzf" ]
   then
       sudo apt install fzf
-      KEYBINDINGS_FILE=/usr/share/doc/fzf/examples/key-bindings.bash
-      EXPECTED_HASH=32a92304092b912ab559586110f005b1
-      # from version 0.44.1
-      if [[ -f "$KEYBINDINGS_FILE" ]]; then
-          if echo "$EXPECTED_HASH  $KEYBINDINGS_FILE" | md5sum -c; then
-              true
-          else
-              echo >&2 "Unexpected file at $KEYBINDINGS_FILE"
-              exit 7
-          fi
-      else
-          echo >&2 "What the heck is going on?"
-          exit 11
+
+      FZF_KEYBINDINGS_FILE=/usr/share/doc/fzf/examples/key-bindings.bash
+      FZF_HASH="$(md5sum "$FZF_KEYBINDINGS_FILE" | awk '{print $1}')"
+      FZF_MODIFIED_FILE="$(dirname "$SELF")"/fzf-key-bindings/$FZF_HASH.bash
+      if ! [[ -f "$FZF_MODIFIED_FILE" ]]; then
+          # Modifying the keybindings file is just a matter of
+          # finding the `bind -m emacs-standard` lines that define `\C-t`,
+          # and prefixing that bit with `\e`
+          echo >&2 "Error: $FZF_MODIFIED_FILE does not exist"
+          exit 7
       fi
   fi
 
