Preliminary stale impl, basic test

diff --git a/base/bin/weesu b/base/bin/weesu
--- a/base/bin/weesu
+++ b/base/bin/weesu
@@ -18,6 +18,11 @@ print_usage_and_exit(){
       - writes a json file to stdout
     weesu merge <file1> <file2>
       - writes a json file to stdout
+    weesu stale
+      - reads json records from stdin and prints
+        a summary of objects that were previously
+        seen at a source but not in the latest
+        viewing of that source
 EOF
     exit 1
 }
@@ -222,6 +227,58 @@ case "$1" in
              <(sort_and_normalize < "$FILE1") \
              <(sort_and_normalize < "$FILE2") \
             | merge_lines
+        ;;
+    "stale")
+        # we first want: a mapping from source IDs to the latest timestamp
+        # associated with them
+        #
+        # then for each SHA, we want to know its latest timestamp for
+        # each source, and compare that with the globally latest timestamp
+        # for each source
+        # could sort -u help with this? "output only the first of an equal run"
+        # I think the only problem is that source_ids can have whitespace (or any
+        # given practical delimeter!); I
+        # wish there were a way to hex encode them OH HEY THERE IS BASE64!!!
+        #
+        #
+        # Okay okay what if we output things so that we arrange for info about
+        # each source to be grouped together; then we dupe information so that
+        # first we get a generic record of all the timestamps for the source,
+        # with the latest one sorted to the top, and then underneath that we have
+        # information for each blob, sorted so that we get the latest timestamp
+        # for that THIS'LL BE GREAT
+        JQ_FILTER='. as $rec
+                   | .seen[]
+                   | [(.source_id | @base64),"source_global",null,.at],
+                     [(.source_id | @base64),"blob",$rec.sha256,.at,.path]'
+        SOURCE_ID=""
+        SOURCE_AT=""
+        jq -cMS "$JQ_FILTER" \
+            | LC_ALL=C sort -u -t , -k 1,3 -r \
+            | while read LINE; do
+                  LINE_TYPE="$(<<< "$LINE" cut -d , -f 2)"
+                  case "${LINE_TYPE:1:-1}" in
+                      "source_global")
+                          SOURCE_ID_HEX_JSON="$(<<< "$LINE" cut -d , -f 1)"
+                          SOURCE_ID="$(echo "${SOURCE_ID_HEX_JSON:2:-1}" | base64 -d)"
+                          SOURCE_AT="$(<<< "$LINE" cut -d , -f 4)"
+                          SOURCE_AT="${SOURCE_AT:1:-2}"
+                      ;;
+                      "blob")
+                          BLOB_AT="$(<<< "$LINE" cut -d , -f 4)"
+                          BLOB_AT="${BLOB_AT:1:-1}"
+                          if [[ "$BLOB_AT" < "$SOURCE_AT" ]]; then
+                              SHA="$(<<< "$LINE" cut -d , -f 3)"
+                              THE_PATH="$(<<< "$LINE" cut -d , -f 5-)"
+                              echo "STALE BLOB (${SHA:1:10}) LAST SEEN IN $SOURCE_ID AT $BLOB_AT AT ${THE_PATH:1:-2}, LATEST SOURCE MEASUREMENT AT $SOURCE_AT"
+                          fi
+                      ;;
+                      *)
+                          >&2 echo "ERROR: THIS IS IMPOSSIBLE: $(printf %q "$LINE_TYPE")"
+                          exit 42
+                      ;;
+                  esac
+        done
         ;;
     *)
         print_usage_and_exit
