Make this extensible somehow

diff --git a/base/.githooks.symlink/pre-commit b/base/.githooks.symlink/pre-commit
--- a/base/.githooks.symlink/pre-commit
+++ b/base/.githooks.symlink/pre-commit
@@ -1,8 +1,21 @@
 #!/usr/bin/env bash
 
+set -e
+
 # Breaking up the forbidden word here so that this hook doesn't catch
 # itself
 if git --no-pager grep "NO"COMMIT >&2; then
     echo >&2 $'\n'"As you can see above, the repo has NO""COMMIT in it, which is not okay."
     exit 1
 fi
+
+HOOKSDIR="$(dirname "$0")"
+
+for file in "$HOOKSDIR"/pre-commit.*; do
+    if [[ -x "$file" ]]; then
+        "$file"
+    else
+        echo >&2 "Can't run $file because it is not executable"
+        exit 9
+    fi
+done
