Two embetterments

diff --git a/base/.githooks.symlink/pre-commit b/base/.githooks.symlink/pre-commit
--- a/base/.githooks.symlink/pre-commit
+++ b/base/.githooks.symlink/pre-commit
@@ -2,6 +2,8 @@
 
 set -Eeou pipefail
 
+NO_COMMIT_START=$(date +%s%3N)
+
 GREP_PATTERN="(?i)\bno[-_ ]?commit\b"
 
 TOTAL_MATCHES=0
@@ -16,6 +18,12 @@ while read FILE; do
     TOTAL_MATCHES=$((TOTAL_MATCHES + 1))
 done < <(git-cached-grep-staged "$GREP_PATTERN")
 
+NO_COMMIT_DURATION=$(($(date +%s%3N) - $NO_COMMIT_START))
+
+if [[ $NO_COMMIT_DURATION -gt 250 ]]; then
+    printf >&2 $'\u001b'"[31m(grepping for NO"" COMMIT took %.3fs)"$'\u001b'"[0m\n" $(python -c "print($NO_COMMIT_DURATION / 1000.0)")
+fi
+
 if [[ $TOTAL_MATCHES -gt 0 ]]; then
     echo -e >&2 "\u001b[31;1mTHAT COMMIT HAS \"NO ""COMMIT\" IN IT,\nWHAT KIND OF MONSTER ARE YOU!!??1!\u001b[0m"
 fi
@@ -23,10 +31,14 @@ fi
 HOOKSDIR="$(dirname "$0")"
 
 for file in "$HOOKSDIR"/pre-commit.*; do
-    if [[ -x "$file" ]]; then
-        "$file"
-    else
-        echo >&2 "Can't run $file because it is not executable"
-        exit 9
+    # need this extra check for when nothing matches; I'm not sure of
+    # a cleaner way to avoid it
+    if [[ -e "$file" ]]; then
+        if [[ -x "$file" ]]; then
+            "$file"
+        else
+            echo >&2 "Can't run $file because it is not executable"
+            exit 9
+        fi
     fi
 done
